name: auth
description: A sample command-line application.
version: 1.0.0


environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  postgres: ^3.1.2
  shelf: ^1.4.1
  shelf_router: ^1.0.0
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.13.0


dev_dependencies:
  lints: ^3.0.0
  melos: ^5.3.0
  test: ^1.24.0
  shelf_router_generator: ^1.1.0
  build_runner:


